baseURL = "https://zahkthar.github.io/"
title = "Zahkthar"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    metaDescription = "Zahkthar - Blog Électronique & Informatique"
    author = "Zahkthar"
    description = "Auteur"
    logo = "https://i.ibb.co/kG74Q7F/Logo-Zahkthar.png"
    favicon = "https://i.ibb.co/kG74Q7F/Logo-Zahkthar.png"
    portrait = "https://i.ibb.co/kG74Q7F/Logo-Zahkthar.png"
    bio = """
    
    Ancien étudiant en électronique et actuel étudiant en informatique, je publie ici "régulièrement" des articles traitant des deux domaines.
    Ils traiteront donc principalement d'électronique et de programmation, particulièrement embarquée. Un ordre de lecture est proposé
    <a href="post/informations/informations_vous-ne-savez-pas-par-ou-commencer/" style="text-decoration: underline;">ici</a>.
    
    """
    copyright = "Copyright © 2023, Zahkthar; tous droits réservés."


[[menu.main]]
    identifier = "about"
    name = "A propos"
    url = "/about/"
    weight = 10
    

[[menu.footer]]
    identifier = "home"
    name = "Accueil"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "fabriceSincere"
    name = "Fabrice Sincère"
    url = "http://fabrice.sincere.pagesperso-orange.fr/"
    weight = 2

[[menu.footer]]
    identifier = "sonelec"
    name = "Sonelec"
    url = "https://www.sonelec-musique.com/electronique.html"
    weight = 3

[taxonomies]
category = "Catégories"
series = "Séries"
tag = "Étiquettes"

[[menu.icon]]
    url = "https://github.com/Zahkthar"
    name = "chevron-right"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Zahkthar"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    name = "music"
    weight = 3

[[menu.icon]]
    url = "https://github.com/Zahkthar"
    name = "chevron-left"
    weight = 4